# Generated by Django 4.0.4 on 2022-05-17 17:24

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('myapp', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='feature',
            name='desc',
        ),
    ]
